### ISSUE TITLE
Re-add `nix flake check` CI job

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel.nix#10]
A reminder to re-add the following job once [this upstream issue](https://github.com/NixOS/nix/issues/4265) is resolved:

```yaml
  nix-flake-check:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: mitchmindtree-fuellabs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --no-update-lock-file
```

Currently, we still check builds for each package, but the `nix flake check` is useful for quickly checking the validity of the flake itself for all targets.
