### ISSUE TITLE
Create a github action that uses `fuel.nix` to install forc

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/fuel.nix#66]
This would give us an idea of whether `fuel.nix` could be a viable replacement for `fuelup` in CI, in terms of latency to install forc.

**Comment by mitchmindtree** [comment]
Just for reference, today downstream users should already be able to use tools from fuel.nix in CI actions with something like this:

```yml
jobs:
  my-build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-substituters = https://fuellabs.cachix.org
            extra-trusted-public-keys = fuellabs.cachix.org-1:3gOmll82VDbT7EggylzOVJ6dr0jgPVU/KMN6+Kf8qx8=
      - run: nix shell github:fuellabs/fuel.nix#forc-0-39-0
      # Following steps now have `forc` version `0.39.0` available.
      - run: forc build
```

But yes, it would be great to test latency, and perhaps provide some wrapper action that takes care of the cachix installation with the necessary binary cache etc.
